openapi: 3.0.3
info:
title: Minimal API
version: 1.0.0
paths:
/ping:
get:
summary: Health check
responses:
'200':
description: OK
content:
application/json:
schema:
type: object
properties:
pong:
type: boolean
example: true